print("Day 3: 02/09/2023")
# Modules: Modules are used to use the another's code in our program
# There are 2 types of modules
# 1. Builtin Modules
# 2. External Moduless


# Modules are well tested and written by experts
# It will save our time if we use modules in our program

# for installing any module we have use pip command in terminal example: pip install pandas   it will install module named as pandas
# we can use module by importing it using import modulename

import pandas #it is an external module we have installed it
print("Hii")


import hashlib #it is Builtin module so we don't have to install it
print("Hello")